### ISSUE TITLE
Email Formatting 

### ISSUE THREAD

**Issue by tunnell** [RiceAstroparticleLab/xenon-users-web#18]
For the approval emails:

`The following request has been approved by José Matias-Lopes:

a) Name: XXXX XXXX
b) Institute: XXXXX
c) Position: Thesis Student
d) Time: 100%
e) Tasks: Analysis
f) Start date: Tue Jun 15 2021 02:00:00 GMT+0200 (CEST)

f) End date: Tue Jun 14 2022 02:00:00 GMT+0200 (CEST)
XENON User Management`

I got the following feedback:

`Just noticed you have twice the bullet point “f” and an empty line in case you want to correct the format of the automatic email`

**Comment by ymart2** [comment]
Issue fixed in https://github.com/RiceAstroparticleLab/xenon-users-web/commit/18ff1dc470c9f5d4445c897af17732391d028b64 and https://github.com/RiceAstroparticleLab/xenon-users-web/commit/36f4897986b0bc8393de4d5dd804b536e94e1636

Additionally, these commits removed "at [institute]" in the new user email and update email in order to reduce confusion. For example, the line `XXXX XXXX's information has been updated by XXXX XXXX at INSTITUTE. `
will now read `XXXX XXXX's information has been updated by XXXX XXXX`.
